### ISSUE TITLE
Provide normal unix-like text output

### ISSUE THREAD

**Issue by winmillwill** [jmespath/jp#2]
There doesn't seem to be any way to output a flat list as a set of lines. Perhaps the -u option should handle flat lists this way, or we could have some other option, or even a jmespath function like 'echo' so that you could do something like:

```
jp 'foo.bar[] | echo(@)' -f foo.json
```

where foo.json like:

```
{
  "foo": {
    "bar": [
      "bang",
      "bling",
      "baz"
    ],
    "zow": ...
  }
}
```

we would get:

```
bang
bling
baz
```

which is suitable for bash loops and xargs and the like.

Apologies if I've missed what should have been an obvious way to achieve this.

**Comment by jamesls** [comment]
I wouldn't call it obvious, but you can use the [join](http://jmespath.org/specification.html#join) function to create a list separated by newlines.  This will get the output you want:

```
$ echo '{"foo": {"bar": ["bang", "bling", "baz"]}}' | ./jp -u 'join(`"\n"`, foo.bar)'
bang
bling
baz
```

The reason the first argument is ``"\n"`` instead of just the literal string `'\n'` is because the literal string doesn't support escape sequences so `'\n'` is interpreted literally as `\` + `n` (0x5c 0x63).  The ``"\n"`` 
 part is saying that everything between the ``...`` should be interpreted as JSON, and the JSON string "\n" will be interpreted as the actual newline char 0xa instead of 0x5c 0x63.

Let me know if you have any other questions.  I'll also add this example to the README.

**Comment by vielmetti** [comment]
So I can't help but compare with the `jq` tool which is very close in spirit to `jp` but has a slightly different syntax. If you feed `jq` with

``` shell
% echo '{"foo": {"bar": ["bang", "bling", "baz"]}}' | jq -r  '.foo.bar[]'
bang
bling
baz
```

The `jq -r` is like `jp -u`, if you're trying to keep both systems in mind at the same time. 

More on jq at https://github.com/stedolan/jq . Both tools are awesome, just that they've evolved a little differently to solve the same task.
