### ISSUE TITLE
quote type matters

### ISSUE THREAD

**Issue by GavinB-hpe** [jmespath/jp#21]
Given input of : 
```
{
  "machines": [
    {"name": "a", "state": "running"},
    {"name": "b", "state": "stopped"},
    {"name": "b", "state": "running"}
  ]
}
```

I would expect these 2 commands to give the same result, but they don't. 
```
$ cat toto3.json  | jp 'machines[?state == "running"].name'
[]
$ cat toto3.json  | jp "machines[?state == 'running'].name"
[
  "a",
  "b"
]
```

Single quotes are specifically mentioned as being the recommended approach due to shell escapes, but plainly they don't work the way that might (naively?) be expected.

**Comment by rarylson** [comment]
I don't think it's a bug. As far as I know, this is the expected behavior in JMESPath: https://github.com/jmespath/jmespath.php/issues/26#issuecomment-169457198

> Double quotes are reserved for selecting elements from an object that may contain special characters. For example, if I have a json document {"foo.bar": "baz"} and I wanted the value of "foo.bar", then I would need to place "foo.bar" in double quotes to prevent JMESPath from treating the "." as a subexpression. So given the expression "foo.bar", JMESPath will return "baz".

> Raw string literals only work with single quotes -- e.g., 'foo.bar' will create the literal value of a string containing "foo.bar".

The documentation also only shows examples using single quotes for raw strings.

Example:

```
locations[?state == 'WA'].name | sort(@)[-2:] | {WashingtonCities: join(', ', @)}
```

Note that there is NO such a thing like:

```
locations[?state == "WA"].name | sort(@)[-2:] | {WashingtonCities: join(", ", @)}
```

The line above is wrong and it's not gonna work!

Link with more examples: https://jmespath.org/examples.html

One way to use single quotes both in Bash and in JMESPath is doing something like: https://stackoverflow.com/a/1250279/2530295

It seems strange, but it works!

In your example:

```
$ cat toto3.json  | jp 'machines[?state == '"'"'running'"'"'].name'
[
  "a",
  "b"
]
```

**Comment by jamesls** [comment]
Closing out old issue, great explanation!
